services:
  afrisinc_web_prod:
    image: ghcr.io/${GHCR_OWNER}/afrisinc-web:${IMAGE_TAG}
    container_name: afrisinc-web-prod
    env_file:
      - .env
    ports:
      - "8085:8090"
    restart: unless-stopped
    environment:
      - VITE_API_URL=${VITE_API_URL}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8090"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - afrisinc_net

networks:
  afrisinc_net:
    driver: bridge
